version: '2'
services:
    #  ssl_nginx:
    #    image: ssl_nginx
    #    build: ssl_nginx
    #    ports:
    #    - 443:443
    #    - 80:80
  app:
    image: ssl_nginx
    volumes:
    - ./app/www/:/www/
    expose:
    - 443
  auth:
    image: ssl_nginx
    volumes:
    - ./authentication/www/:/www/
    expose:
    - 443
  proxy:
    build: ./proxy/
    ports:
    - 443:443
    restart: always
